
import { AIModel, StoryCreationSettings, Story, Volume, Chapter, Tag } from '../types';
import { tags } from './dummyData';

// This is a placeholder service that would be replaced with actual API calls
export const aiService = {
  generateStory: async (settings: StoryCreationSettings): Promise<Story> => {
    // In a real implementation, this would call an API
    console.log('Generating story with settings:', settings);
    
    // Simulate API delay
    await new Promise(resolve => setTimeout(resolve, 2000));
    
    // Create volumes and chapters
    const volumes: Volume[] = [];
    for (let v = 0; v < settings.volumeCount; v++) {
      const chapters: Chapter[] = [];
      for (let c = 0; c < settings.chaptersPerVolume; c++) {
        chapters.push({
          id: `chapter-${v}-${c}`,
          title: `Chapter ${c + 1}: ${getSampleChapterTitle()}`,
          content: getSampleChapterContent(),
          order: c + 1,
          volumeId: `volume-${v}`,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString()
        });
      }
      
      volumes.push({
        id: `volume-${v}`,
        title: `Volume ${v + 1}: ${getSampleVolumeTitle()}`,
        order: v + 1,
        chapters: chapters,
        storyId: 'new-story',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      });
    }
    
    // Get tags from selected IDs
    const storyTags: Tag[] = settings.tags.map(tagId => 
      tags.find(t => t.id === tagId) || tags[0]
    );
    
    // Generate a new story
    const newStory: Story = {
      id: `story-${Date.now()}`,
      title: settings.title || 'My New AI Story',
      synopsis: settings.synopsis || 'A fascinating tale generated by AI.',
      coverImage: settings.coverImage || 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21',
      authorId: 'current-user',
      authorName: 'Current User',
      tags: storyTags,
      volumes: volumes,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      views: 0,
      likes: 0,
      isPublished: false
    };
    
    return newStory;
  },
  
  generateCoverImage: async (synopsis: string, tags: string[]): Promise<string> => {
    // In a real implementation, this would call an AI image generation API
    console.log('Generating cover image based on:', { synopsis, tags });
    
    // Simulate API delay
    await new Promise(resolve => setTimeout(resolve, 1500));
    
    // Return a placeholder image
    const placeholders = [
      'https://images.unsplash.com/photo-1649972904349-6e44c42644a7',
      'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158',
      'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5',
      'https://images.unsplash.com/photo-1470813740244-df37b8c1edcb',
      'https://images.unsplash.com/photo-1500375592092-40eb2168fd21',
      'https://images.unsplash.com/photo-1426604966848-d7adac402bff',
      'https://images.unsplash.com/photo-1523712999610-f77fbcfc3843'
    ];
    
    return placeholders[Math.floor(Math.random() * placeholders.length)];
  },
  
  updateChapter: async (chapterId: string, newContent: string): Promise<Chapter> => {
    // In a real implementation, this would update the chapter in the database
    console.log('Updating chapter:', { chapterId, newContent });
    
    // Simulate API delay
    await new Promise(resolve => setTimeout(resolve, 500));
    
    return {
      id: chapterId,
      title: 'Updated Chapter',
      content: newContent,
      order: 1,
      volumeId: 'volume-id',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    };
  }
};

// Helper functions to generate sample content
function getSampleChapterTitle(): string {
  const titles = [
    'The Beginning',
    'Dark Horizons',
    'First Encounter',
    'The Discovery',
    'Hidden Secrets',
    'The Challenge',
    'Lost and Found',
    'New Allies',
    'Ancient Powers',
    'The Revelation'
  ];
  return titles[Math.floor(Math.random() * titles.length)];
}

function getSampleVolumeTitle(): string {
  const titles = [
    'The Awakening',
    'Dark Tides',
    'Rising Power',
    'The Journey Begins',
    'Shadows and Light',
    'The Turning Point',
    'Echoes of the Past',
    'New Horizons',
    'The Final Test',
    'Destiny Calls'
  ];
  return titles[Math.floor(Math.random() * titles.length)];
}

function getSampleChapterContent(): string {
  return `The morning sun cast long shadows across the ancient stones of the forgotten temple. As Maya brushed away centuries of dust from the inscriptions, a sense of excitement welled up within her. This could be it—the discovery she had spent her entire career searching for.

"Professor! Come look at this," her assistant called from deeper within the temple.

Maya carefully set down her brush and made her way through the narrow corridor. The air was thick with the scent of earth and stone, and the only sound was the soft padding of her footsteps against the worn floor.

Her assistant, Liam, stood before a wall covered in symbols that seemed to shimmer even in the dim light of their lanterns.

"I've never seen anything like this," Liam said, his voice barely above a whisper. "The symbols... they're changing."

Maya leaned closer, her heart racing. He was right. The symbols were shifting subtly, rearranging themselves as if alive. As she watched, they began to form words in a language she somehow understood despite never having seen it before.

"Seeker," the wall seemed to say, "the veil between worlds grows thin."

A chill ran down her spine as the meaning of the words sank in. This wasn't just an archaeological discovery—it was something far more profound. The stories she had dismissed as myths and legends suddenly seemed much more real.

"We need to document everything," she said, trying to keep her voice steady. "And then... I think we need to be very careful about what happens next."

Little did she know that the wall's message was just the beginning. The forgotten realms were awakening, and Maya would soon find herself caught between two worlds, with the fate of both hanging in the balance.`;
}
